#!/bin/sh
# Uninstall fcron under SysV system.
#


PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"
if test -d /usr/ucb; then
    PATH=/usr/ucb:$PATH
fi

if test `uname -s` = "FreeBSD"; then
  rm -f /usr/local/etc/rc.d/fcron.sh
else
  ROOTDIR=""
  if test -f /etc/rc.d/init.d/fcron; then
    ROOTDIR="/etc/rc.d"
  elif test -f /etc/init.d/fcron; then
    ROOTDIR="/etc"
  fi
  if test $ROOTDIR != ""; then
    rm -f $ROOTDIR/init.d/fcron

    for i in 0 1 2 3 4 5 6
    do
    rm -f $ROOTDIR/rc$i.d/???fcron
    done

  else
    echo
    echo "You should delete fcron from your boot script manually"
    echo
  fi
fi

