.build:
  extends: .rules
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    COMPONENT: "testing"
  script:
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
          "auths": {
              "https://index.docker.io/v1/": {
                  "auth": "${AUTH_STRING_DOCKER_HUB}"
              },
              "$CI_REGISTRY": {
                  "username": "${CI_REGISTRY_USER}",
                  "password": "${CI_REGISTRY_PASSWORD}"
              }
          }
      }
      EOF
    - |
      echo "********************************************"
      echo "Build details"
      echo "============================================"
      echo "Flavour ${PASSBOLT_FLAVOUR:-local}"
      echo "Commit  ${UPSTREAM_COMMIT_SHA:-latest}"
      echo "********************************************"
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --build-arg PASSBOLT_FLAVOUR="$PASSBOLT_FLAVOUR" \
        --build-arg PASSBOLT_COMPONENT="$COMPONENT" \
        --build-arg SUPERCRONIC_ARCH="${SUPERCRONIC_ARCH}" \
        --build-arg SUPERCRONIC_SHA1SUM="${SUPERCRONIC_SHA1SUM}" \
        --dockerfile $CI_PROJECT_DIR/$DOCKERFILE_PATH \
        --custom-platform $PLATFORM \
        --destination $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR:-local}-${DOCKER_TAG}-$(date +%s) \
        --destination $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR:-local}-${DOCKER_TAG}-latest

.stable-build:
  extends: .build
  variables:
    COMPONENT: "stable"
    PASSBOLT_FLAVOUR: "ce"
    OPPOSITE_FLAVOUR: "pro"

.stable-build-pro:
  extends: .build
  variables:
    COMPONENT: "stable"
    PASSBOLT_FLAVOUR: "pro"
    OPPOSITE_FLAVOUR: "ce"

build-ce-stable-docker:
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: 642f4f5a2b67f3400b5ea71ff24f18c0a7d77d49
    PLATFORM: "linux/amd64"

build-ce-stable-rootless:
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: 642f4f5a2b67f3400b5ea71ff24f18c0a7d77d49
    PLATFORM: "linux/amd64"

build-pro-stable-docker:
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: 642f4f5a2b67f3400b5ea71ff24f18c0a7d77d49
    PLATFORM: "linux/amd64"

build-pro-stable-rootless:
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: 642f4f5a2b67f3400b5ea71ff24f18c0a7d77d49
    PLATFORM: "linux/amd64"

build-ce-stable-docker-arm64-v8:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 0b658d66bd54cf10aeccd9bdbd95fc7d9ba84a61

build-ce-stable-rootless-arm64-v8:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 0b658d66bd54cf10aeccd9bdbd95fc7d9ba84a61

build-pro-stable-docker-arm64-v8:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 0b658d66bd54cf10aeccd9bdbd95fc7d9ba84a61

build-pro-stable-rootless-arm64-v8:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 0b658d66bd54cf10aeccd9bdbd95fc7d9ba84a61

build-ce-stable-docker-arm-v5:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-ce-stable-rootless-arm-v5:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-pro-stable-docker-arm-v5:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-pro-stable-rootless-arm-v5:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-ce-stable-docker-arm-v7:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-ce-stable-rootless-arm-v7:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-pro-stable-docker-arm-v7:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be

build-pro-stable-rootless-arm-v7:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 4f625d77d2f9a790ea4ad679d0d2c318a14ec3be
